CREATE TABLE public.pokemon_ability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary KEY,
    raw_id VARCHAR(13) NOT NULL,
    user_id VARCHAR(7) NOT NULL,
    pokemon_ability_id VARCHAR(4) NOT NULL,
    effect TEXT,
    "language" JSON,
    short_effect TEXT
);